use aor_db::sql;
sql!(pub UserByEmail,portable,"migrations","SELECT id, email, password_hash, verified, epoch FROM aor_users WHERE email = $1");
sql!(pub InsertUser,portable,"migrations","INSERT INTO aor_users (id, email, password_hash, verified, epoch) VALUES ($1, $2, $3, $4, $5) ON CONFLICT (email) DO NOTHING");
sql!(pub LockUser,portable,"migrations","UPDATE aor_users SET epoch = epoch WHERE id = $1 AND epoch = $2 RETURNING id");
sql!(pub InsertSession,portable,"migrations","INSERT INTO aor_sessions (token_hash, user_id, csrf_hash, created_at, seen_at, expires_at, epoch) VALUES ($1, $2, $3, $4, $5, $6, $7)");
sql!(pub FindSession,portable,"migrations","SELECT s.user_id, s.csrf_hash, s.created_at, s.seen_at, s.expires_at, s.epoch FROM aor_sessions AS s INNER JOIN aor_users AS u ON u.id = s.user_id WHERE s.token_hash = $1 AND s.epoch = u.epoch AND u.verified = $2");
sql!(pub TouchSession,portable,"migrations","UPDATE aor_sessions SET seen_at = $1 WHERE token_hash = $2 AND seen_at > $3 AND expires_at > $4");
sql!(pub DeleteSession,portable,"migrations","DELETE FROM aor_sessions WHERE token_hash = $1");
sql!(pub RevokeSessions,portable,"migrations","DELETE FROM aor_sessions WHERE user_id = $1");
sql!(pub RevokeApi,portable,"migrations","DELETE FROM aor_api_tokens WHERE user_id = $1");
sql!(pub AdvanceEpoch,portable,"migrations","UPDATE aor_users SET epoch = epoch + 1 WHERE id = $1");
sql!(pub InsertApi,portable,"migrations","INSERT INTO aor_api_tokens (token_hash, user_id, scopes, expires_at, epoch) VALUES ($1, $2, $3, $4, $5)");
sql!(pub FindApi,portable,"migrations","SELECT t.user_id, t.scopes, t.epoch FROM aor_api_tokens AS t INNER JOIN aor_users AS u ON u.id = t.user_id WHERE t.token_hash = $1 AND t.epoch = u.epoch AND t.expires_at > $2 AND u.verified = $3");
sql!(pub DeleteApi,portable,"migrations","DELETE FROM aor_api_tokens WHERE token_hash = $1 AND user_id = $2");
sql!(pub InsertOneTime,portable,"migrations","INSERT INTO aor_one_time (token_hash, user_id, purpose, expires_at) VALUES ($1, $2, $3, $4)");
sql!(pub ConsumeOneTime,portable,"migrations","DELETE FROM aor_one_time WHERE token_hash = $1 AND purpose = $2 AND expires_at > $3 RETURNING user_id");
sql!(pub VerifyEmail,portable,"migrations","UPDATE aor_users SET verified = $1 WHERE id = $2");
sql!(pub ResetPassword,portable,"migrations","UPDATE aor_users SET password_hash = $1, epoch = epoch + 1 WHERE id = $2");
sql!(pub RevokeOneTime,portable,"migrations","DELETE FROM aor_one_time WHERE user_id = $1");
