[package]
name = "aor-archive"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
aor-db = { path = "../../crates/aor-db" }
aor-migrate = { path = "../../crates/aor-migrate" }
serde.workspace = true
sha2.workspace = true
aor-http = { path = "../../crates/aor-http" }
tokio.workspace = true

aor-router = { path = "../../crates/aor-router" }
aor-tmpl = { path = "../../crates/aor-tmpl" }
aor-dev = { path = "../../crates/aor-dev" }
serde_json.workspace = true
[lints]
workspace = true

[build-dependencies]
aor-migrate = { path = "../../crates/aor-migrate", default-features = false }
